# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_jJxmFcTbieqKyCk-qoWXwgJef5PHDik
"""

print("Hello World")

print(300*300)

print("I can print this and also a calculation", 3.14*3.14)

print("My name is Sylvia, and Nice to meet you!","Peach is my favorite friuts")

"""等号左边是变量参数，右边是被赋予的值，也就是我们可以随时引用；"""

name = "Sylvia"
age = 22
print("Hi,my name is",name,"and I am",22)

"""【Manipulating Variables】操作变量：因为变量只记得最后你赋予他的值，所以可以重新定义变量"""

number = 5
number = number + 1
x = 2
y = x
x = 3
print(number,y)

"""【Variable Type: 变量类型】
一共有4个不同类型：String字节、Integer整数、Float浮点数、Bool布尔；我们可以用type()函数测试不同变量的类型
"""

pi = 3.14
days_in_week = 7
greeting = "Howdy"
print(type(days_in_week),type(pi),type(greeting))
type(pi)

"""可以用int(); float();以及str()来实现变量中的转换；"""

pi = 3.14
radius = 5
Area = pi * radius**2
Circumference = 2 * pi * radius
print(Area,Circumference)